### PR TITLE
Bump deps, build with go 1.19

### PR DESCRIPTION
**Pull request by mrueg**
This bumps to use a more recent go version for building and testing as well the dependencies that are used by go-keyring.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@mrueg Thanks. We might as well update to latest stable Go 1.19 while we're at it.

**Comment by mrueg** [comment]
> @mrueg Thanks. We might as well update to latest stable Go 1.19 while we're at it.

Done!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
