### PR TITLE
Fix Windows crash by bumping wincred

### PR DESCRIPTION
**Pull request by mislav**
For some Go applications, reading a stored credential from wincred could result in a crash because both the returned credential pointer and the error value would be nil, even though the credential technically exists in wincred storage. This was [fixed upstream in the wincred library](https://github.com/danieljoos/wincred/releases/tag/v1.2.0).

⚠️ Note that the minimum Go version required by `danieljoos/wincred` is now 1.18. The appveyor build fails as a result due to its go version `go1.13.3`

Fixes https://github.com/zalando/go-keyring/issues/53

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Will remove appvoyer in #93 and fix the FreeBSD build in #94

**Comment by szuecs** [comment]
Ah no close/reopen does not work, you have to fetch and rebase on master branch.
We merged all the mentioned PRs.

**Comment by mikkeloscar** [comment]
I have rebased the PR

**Comment by mikkeloscar** [comment]
:+1:

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
