### PR TITLE
Export ErrUnsupportedPlatform error

### PR DESCRIPTION
**Pull request by timbunce**
Export ErrUnsupportedPlatform error

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Thanks! Can you signoff the commit and add some text to the PR description to make our bots happy? :)

**Comment by szuecs** [comment]
`git commit --amend --signoff    `should do the trick and then push -f

**Comment by timbunce** [comment]
I've done the `git commit --amend --signoff`.
I'm not sure what to make of "PR's body failed check 'contains-issue-number'", I trust you can look after it.
Sorry for the delay.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
