### PR TITLE
Add a mocked provider

### PR DESCRIPTION
**Pull request by comebackoneyear**
We needed a mocked provider for our integration tests and I thought this might be useful for someone else too, hence the pull request.

Open to feedback.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Thanks, looks great. Maybe you want to add a small note to the README about this?

**Comment by comebackoneyear** [comment]
@mikkeloscar Added a note about it

**Comment by mikkeloscar** [comment]
Thanks!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
