### PR TITLE
feat: add DeleteAll methods to keyring

### PR DESCRIPTION
**Pull request by avallete**
Possible implementation of #111

### CODE REVIEW

**Comment by szuecs** [comment]
@avallete please sign-off all commits to fix DCO check, thanks!

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
It will likely take some time until @mikkeloscar is back, max one month, FYI.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by avallete** [comment]
Hey @mikkeloscar 

Sorry to dig this one up, but I wonder if there is a release of the package including this feature is scheduled and when should it come around. So I can get myself a reminder and upgrade to it in our codebase.

**Comment by mikkeloscar** [comment]
New release: https://github.com/zalando/go-keyring/releases/tag/v0.2.6

**Pull request merged**
